frequency: Weekly, Ending Saturday
geography: State
name: HighPropensityBusinessApplications
national_exists: false
release: 468
seasonally_adjusted: true
state_codes:
  AK: HBUSAPPWNSAAK
  AL: HBUSAPPWNSAAL
  AR: HBUSAPPWNSAAR
  AZ: HBUSAPPWNSAAZ
  CA: HBUSAPPWNSACA
  CO: HBUSAPPWNSACO
  CT: HBUSAPPWNSACT
  DC: HBUSAPPWNSADC
  DE: HBUSAPPWNSADE
  FL: HBUSAPPWNSAFL
  GA: HBUSAPPWNSAGA
  HI: HBUSAPPWNSAHI
  IA: HBUSAPPWNSAIA
  ID: HBUSAPPWNSAID
  IL: HBUSAPPWNSAIL
  IN: HBUSAPPWNSAIN
  KS: HBUSAPPWNSAKS
  KY: HBUSAPPWNSAKY
  LA: HBUSAPPWNSALA
  MA: HBUSAPPWNSAMA
  MD: HBUSAPPWNSAMD
  ME: HBUSAPPWNSAME
  MI: HBUSAPPWNSAMI
  MN: HBUSAPPWNSAMN
  MO: HBUSAPPWNSAMO
  MS: HBUSAPPWNSAMS
  MT: HBUSAPPWNSAMT
  NC: HBUSAPPWNSANC
  ND: HBUSAPPWNSAND
  NE: HBUSAPPWNSANE
  NH: HBUSAPPWNSANH
  NJ: HBUSAPPWNSANJ
  NM: HBUSAPPWNSANM
  NV: HBUSAPPWNSANV
  NY: HBUSAPPWNSANY
  OH: HBUSAPPWNSAOH
  OK: HBUSAPPWNSAOK
  OR: HBUSAPPWNSAOR
  PA: HBUSAPPWNSAPA
  RI: HBUSAPPWNSARI
  SC: HBUSAPPWNSASC
  SD: HBUSAPPWNSASD
  TN: HBUSAPPWNSATN
  TX: HBUSAPPWNSATX
  UT: HBUSAPPWNSAUT
  VA: HBUSAPPWNSAVA
  VT: HBUSAPPWNSAVT
  WA: HBUSAPPWNSAWA
  WI: HBUSAPPWNSAWI
  WV: HBUSAPPWNSAWV
  WY: HBUSAPPWNSAWY
state_pulled:
  AK: 01-01-2011
  AL: 01-01-2011
  AR: 01-01-2011
  AZ: 01-01-2011
  CA: 01-01-2011
  CO: 01-01-2011
  CT: 01-01-2011
  DC: 01-01-2011
  DE: 01-01-2011
  FL: 01-01-2011
  GA: 01-01-2011
  HI: 01-01-2011
  IA: 01-01-2011
  ID: 01-01-2011
  IL: 01-01-2011
  IN: 01-01-2011
  KS: 01-01-2011
  KY: 01-01-2011
  LA: 01-01-2011
  MA: 01-01-2011
  MD: 01-01-2011
  ME: 01-01-2011
  MI: 01-01-2011
  MN: 01-01-2011
  MO: 01-01-2011
  MS: 01-01-2011
  MT: 01-01-2011
  NC: 01-01-2011
  ND: 01-01-2011
  NE: 01-01-2011
  NH: 01-01-2011
  NJ: 01-01-2011
  NM: 01-01-2011
  NV: 01-01-2011
  NY: 01-01-2011
  OH: 01-01-2011
  OK: 01-01-2011
  OR: 01-01-2011
  PA: 01-01-2011
  RI: 01-01-2011
  SC: 01-01-2011
  SD: 01-01-2011
  TN: 01-01-2011
  TX: 01-01-2011
  UT: 01-01-2011
  VA: 01-01-2011
  VT: 01-01-2011
  WA: 01-01-2011
  WI: 01-01-2011
  WV: 01-01-2011
  WY: 01-01-2011
units: Number
